### ISSUE TITLE
Remove the "X"

### ISSUE THREAD

**Issue by Fastidious** [ksylvest/jquery-lighter#11]
How would I go about removing the "close zoomed image" (X)? Clicking outside the zoomed image goes back, so I do not need the X. Thanks in advance.

**Comment by ksylvest** [comment]
The easiest way to do this is by CSS:

``` css
.lighter-close { 
  display: none; 
}
```
